## BIRDCLEF 2024 - Rami El Wazzi & Sacha Guenoun

### Partie 2 - Hypothèse d'utilisation des propriétés du son

#### Objectif du projet : entrainer un réseau de neurones permettant de reconnaitre un oiseau grâce à son cri.

In [19]:
import librosa
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import multiprocessing as mp
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
import tensorflow as tf

In [20]:
df_meta = pd.read_csv("./birdclef-2024/train_metadata.csv")

In [21]:
df_meta.head(3)

,primary_label,secondary_labels,type,latitude,longitude,scientific_name,common_name,author,license,rating,url,filename
0,asbfly,[],['call'],39.2297,118.1987,Muscicapa dauurica,Asian Brown Flycatcher,Matt Slaymaker,Creative Commons Attribution-NonCommercial-Sha...,5.0,https://www.xeno-canto.org/134896,asbfly/XC134896.ogg
1,asbfly,[],['song'],51.4030,104.6401,Muscicapa dauurica,Asian Brown Flycatcher,Magnus Hellström,Creative Commons Attribution-NonCommercial-Sha...,2.5,https://www.xeno-canto.org/164848,asbfly/XC164848.ogg
2,asbfly,[],['song'],36.3319,127.3555,Muscicapa dauurica,Asian Brown Flycatcher,Stuart Fisher,Creative Commons Attribution-NonCommercial-Sha...,2.5,https://www.xeno-canto.org/175797,asbfly/XC175797.ogg
3,asbfly,[],['call'],21.1697,70.6005,Muscicapa dauurica,Asian Brown Flycatcher,vir joshi,Creative Commons Attribution-NonCommercial-Sha...,4.0,https://www.xeno-canto.org/207738,asbfly/XC207738.ogg
4,asbfly,[],['call'],15.5442,73.7733,Muscicapa dauurica,Asian Brown Flycatcher,Albert Lastukhin & Sergei Karpeev,Creative Commons Attribution-NonCommercial-Sha...,4.0,https://www.xeno-canto.org/209218,asbfly/XC209218.ogg
...,...,...,...,...,...,...,...,...,...,...,...,...
24454,zitcis1,[],[''],43.5925,4.5434,Cisticola juncidis,Zitting Cisticola,Chèvremont Fabian,Creative Commons Attribution-NonCommercial-Sha...,5.0,https://xeno-canto.org/845747,zitcis1/XC845747.ogg
24455,zitcis1,[],[''],43.5925,4.5434,Cisticola juncidis,Zitting Cisticola,Chèvremont Fabian,Creative Commons Attribution-NonCommercial-Sha...,4.0,https://xeno-canto.org/845817,zitcis1/XC845817.ogg
24456,zitcis1,[],[''],51.1207,4.5607,Cisticola juncidis,Zitting Cisticola,Wim Jacobs,Creative Commons Attribution-NonCommercial-Sha...,4.0,https://xeno-canto.org/856176,zitcis1/XC856176.ogg
24457,zitcis1,[],[''],41.5607,-8.4236,Cisticola juncidis,Zitting Cisticola,Jorge Leitão,Creative Commons Attribution-NonCommercial-Sha...,4.5,https://xeno-canto.org/856723,zitcis1/XC856723.ogg
24458,zitcis1,[],[''],13.7747,100.8919,Cisticola juncidis,Zitting Cisticola,Sam Hambly,Creative Commons Attribution-NonCommercial-Sha...,5.0,https://xeno-canto.org/858550,zitcis1/XC858550.ogg

In [22]:
df_train = df_meta[["primary_label", "filename"]]

### Constat : entrainer un CNN sur des images s'avère très volumineux et n'est pas forcément l'option la plus optimale. C'est pourquoi on cherche à obtenir des matrices avec les propriétés du son pour chaque audio à la place.

Ce qu'on regarde : 
- **Mel spectrogram** - ce que l'on utilisait déjà à la base, permet de représenter l'amplitude au carré de l'audio (i.e. sa puissance) sur l'échelle des mels.
- **MFCC** (Mel-Frequency Cepstral Coefficients) : regarde la puissance de l'audio sur des courtes périodes. Ici, n_mfcc = 13, donc on coupe l'audio en 13 et on regarde la puissance de l'audio sur l'échelle de mel à chacune de ces périodes.
- **Chroma** : permet de ressortir le pitch (12 valeurs différentes pour chaque demi ton d'une octave) avec le temps.
- **Spectral contrast** : regarde la différence en amplitude entre les "pics" et les "creux" de l'audio
- **Tonnetz** : représente l'espace tonal sous forme de matrice. Cela permet de regarder les différentes composantes harmoniques du signal à des fréquences différentes, et voir leurs liaisons.
- **Spectral centroid/bendwidth/rolloff** : regardent respectivement la fréquence au 'centre' du spectrograme, la largeur de la bande du spectrograme et les différences de fréquences par rapport à la fréquence moyenne.
- **Zero Crossing Rate** : mesure le bruit du signal.

In [24]:
def extract_audio_features_with_path(args):
    ogg_file_path, max_length = args
    return extract_audio_features(ogg_file_path, max_length)

def extract_audio_features(ogg_file_path, max_length=22050*5):
    y, sr = librosa.load(ogg_file_path, sr=None)
    
    # Ensure the audio is of fixed length
    if len(y) < max_length:
        y = np.pad(y, (0, max_length - len(y)), 'constant')
    else:
        y = y[:max_length]
    
    # Extract features
    features = {}

    # Mel spectrogram
    S = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=128, fmax=8000)
    S_dB = librosa.power_to_db(S, ref=np.max)
    features['mel_spectrogram'] = S_dB

    # MFCC
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
    features['mfcc'] = mfcc

    # Chroma feature
    chroma = librosa.feature.chroma_stft(y=y, sr=sr)
    features['chroma'] = chroma

    # Spectral contrast
    spectral_contrast = librosa.feature.spectral_contrast(y=y, sr=sr)
    features['spectral_contrast'] = spectral_contrast

    # Tonnetz
    tonnetz = librosa.feature.tonnetz(y=librosa.effects.harmonic(y), sr=sr)
    features['tonnetz'] = tonnetz

    # Spectral centroid
    spectral_centroid = librosa.feature.spectral_centroid(y=y, sr=sr)
    features['spectral_centroid'] = spectral_centroid

    # Spectral bandwidth
    spectral_bandwidth = librosa.feature.spectral_bandwidth(y=y, sr=sr)
    features['spectral_bandwidth'] = spectral_bandwidth

    # Spectral rolloff
    spectral_rolloff = librosa.feature.spectral_rolloff(y=y, sr=sr)
    features['spectral_rolloff'] = spectral_rolloff

    # Zero crossing rate
    zero_crossing_rate = librosa.feature.zero_crossing_rate(y)
    features['zero_crossing_rate'] = zero_crossing_rate

    # RMS
    rms = librosa.feature.rms(y=y)
    features['rms'] = rms

    return features

In [25]:

# Example usage
audio_features = extract_audio_features('./birdclef-2024/train_audio/asbfly/XC49755.ogg')

# Convert features to a dictionary of DataFrames for better visualization
features_df = {key: pd.DataFrame(value) for key, value in audio_features.items()}

# Display the extracted features
for feature_name, df in features_df.items():
    print(f"\nFeature: {feature_name}")
    display(df.head())  # Using display() from IPython.display for better visualization in Jupyter

Feature: mel_spectrogram

,0,1,2,3,4,5,6,7,8,9,...,206,207,208,209,210,211,212,213,214,215
0,-80.0,-80.0,-80.0,-80.0,-71.131088,-64.629059,-64.798874,-65.517334,-64.943108,-66.595901,...,-68.542099,-62.939037,-61.753532,-64.483032,-63.943806,-68.828239,-75.564331,-80.000000,-69.745407,-58.308243
1,-80.0,-80.0,-80.0,-80.0,-78.152908,-77.862320,-80.000000,-80.000000,-80.000000,-80.000000,...,-66.897888,-64.690094,-63.297081,-61.861931,-62.233372,-65.241409,-66.423172,-74.840057,-68.645630,-57.374527
2,-80.0,-80.0,-80.0,-80.0,-80.000000,-80.000000,-80.000000,-80.000000,-80.000000,-80.000000,...,-61.738167,-63.307991,-63.542484,-68.342438,-66.267380,-65.165840,-68.677383,-73.797440,-69.288124,-58.136021
3,-80.0,-80.0,-80.0,-80.0,-78.352684,-80.000000,-80.000000,-80.000000,-80.000000,-79.861069,...,-64.366806,-71.845596,-70.448761,-73.537865,-71.473488,-71.168457,-72.105133,-69.305962,-67.361351,-57.354900
4,-80.0,-80.0,-80.0,-80.0,-80.000000,-80.000000,-80.000000,-80.000000,-80.000000,-80.000000,...,-73.917877,-80.000000,-76.070702,-72.207718,-73.334587,-75.337097,-80.000000,-70.599457,-68.497894,-58.325111

Feature: mfcc

,0,1,2,3,4,5,6,7,8,9,...,206,207,208,209,210,211,212,213,214,215
0,-695.373413,-695.373413,-695.354370,-680.230347,-643.505615,-619.225769,-591.797607,-570.970276,-563.205383,-558.302429,...,-306.195435,-323.671509,-334.408752,-339.167542,-338.049377,-331.991241,-328.520203,-321.373688,-314.663330,-300.228363
1,0.000000,0.000000,0.000993,-1.203629,-5.267550,-6.745503,-6.516576,-5.824796,-6.088685,-6.661308,...,-41.371971,-18.021278,-13.957634,-14.097694,-14.342091,-13.824339,-19.953579,-27.281540,-24.620070,-22.640427
2,0.000000,0.000000,-0.026895,-17.487478,-48.594490,-65.481277,-84.124863,-95.908478,-98.228439,-101.852119,...,-174.743820,-175.672653,-179.184845,-179.671799,-181.474518,-182.583755,-186.912918,-188.352631,-176.718719,-133.417725
3,0.000000,0.000000,-0.002972,2.805939,12.572544,14.241900,11.571678,11.357302,12.281720,13.987471,...,65.480560,54.011566,45.415138,47.022881,52.940201,50.364639,52.326851,65.001930,67.655037,71.527222
4,0.000000,0.000000,0.026674,8.966082,11.528899,8.192680,3.498781,-2.270909,-9.443661,-8.712378,...,-91.412788,-79.573349,-68.684563,-62.239914,-48.788330,-53.536591,-59.000977,-60.851517,-54.280037,-25.470657

Feature: chroma

,0,1,2,3,4,5,6,7,8,9,...,206,207,208,209,210,211,212,213,214,215
0,0.708294,0.640073,0.707259,0.544579,0.313167,0.284966,0.254466,0.247745,0.324839,0.466124,...,0.114438,0.319022,0.370808,0.189577,0.042638,0.022667,0.024571,0.025156,0.057726,0.065114
1,0.595519,0.761191,0.617285,0.474224,0.340369,0.308571,0.460019,0.379475,0.303072,0.324227,...,0.102003,0.304018,0.354480,0.219087,0.042779,0.023521,0.017317,0.014781,0.018537,0.015970
2,0.703772,0.855086,1.000000,0.511553,0.417635,0.389911,0.582625,0.537955,0.582327,0.628322,...,0.233477,0.346289,0.495336,0.291200,0.052698,0.023576,0.022504,0.014497,0.009743,0.012317
3,0.729621,0.740412,0.929025,0.534931,0.516650,0.398323,0.351357,0.400521,0.466656,0.598876,...,0.588485,0.842825,0.873660,0.598802,0.114322,0.032365,0.044700,0.024819,0.015485,0.013818
4,0.966630,0.828872,0.708723,0.531631,0.500283,0.516987,0.690588,0.737945,0.609317,0.782331,...,0.807133,0.989460,0.916617,0.499404,0.099249,0.059439,0.052223,0.020962,0.019204,0.018052

Feature: spectral_contrast

,0,1,2,3,4,5,6,7,8,9,...,206,207,208,209,210,211,212,213,214,215
0,8.354789,11.055998,18.828671,13.490233,10.935961,17.737949,25.388243,23.359610,17.671988,16.888793,...,11.537279,17.708985,20.112713,13.965326,9.895205,7.356818,12.943917,12.273817,1.991143,0.512271
1,5.655446,9.460600,13.589362,8.253297,6.355060,13.855686,5.488953,9.860992,11.352152,20.052817,...,10.357358,7.098369,13.165182,9.920686,10.515408,9.414201,11.883696,5.564685,6.395933,1.331911
2,7.175263,17.008956,10.132587,9.868055,10.725293,9.491114,13.383151,10.775952,15.808019,12.061584,...,10.227369,11.273113,17.308726,12.270389,16.328030,13.583443,14.426049,16.306095,14.946764,10.478193
3,13.181875,18.487175,7.492489,13.558935,11.697553,16.721773,12.770144,18.760145,14.912206,12.216163,...,10.045216,14.306968,15.011783,14.692562,13.983963,16.310986,12.784040,19.126865,17.829470,11.865270
4,11.863661,11.875510,12.481406,14.705046,15.351458,15.150294,13.763278,11.776819,11.068492,17.253255,...,18.722957,19.851830,14.893244,17.568429,17.895546,21.664872,21.846788,22.297710,16.560607,15.399929

Feature: tonnetz

,0,1,2,3,4,5,6,7,8,9,...,206,207,208,209,210,211,212,213,214,215
0,0.053549,0.046576,0.069057,-0.033938,0.008213,0.029023,0.030646,-0.002728,0.043914,0.068861,...,0.000652,-0.044043,-0.096815,-0.092799,-0.093779,-0.024391,0.022639,0.041813,-0.040458,0.034045
1,0.006453,-0.015780,0.014258,0.041921,0.020128,0.015061,0.021392,-0.037868,-0.028053,0.050517,...,-0.011720,-0.085404,0.003189,-0.085780,0.012057,-0.011803,-0.030609,0.036463,-0.000963,-0.023262
2,0.059750,0.059457,0.074420,0.068720,0.029005,-0.084037,0.049583,-0.014404,0.035721,0.032192,...,0.006173,0.045641,0.028443,-0.021291,-0.084611,0.078510,0.001111,-0.084613,0.032052,-0.095086
3,0.063891,0.044799,0.006855,0.047675,0.045305,0.079124,0.070752,0.129191,0.091020,0.047130,...,-0.062414,-0.093077,0.102964,0.102695,-0.054047,0.059749,-0.066663,0.001458,0.000603,-0.094087
4,-0.003680,-0.011251,0.000642,-0.045971,0.009795,-0.042154,0.018350,0.020736,0.005233,-0.031041,...,-0.034227,-0.024232,-0.041018,-0.120868,-0.063487,0.012695,-0.023469,-0.047408,-0.042899,-0.044499

Feature: spectral_centroid

,0,1,2,3,4,5,6,7,8,9,...,206,207,208,209,210,211,212,213,214,215
0,7677.594528,6883.725503,5391.344916,4644.819401,4256.435294,4117.689976,4004.929147,3984.25724,4061.659935,4006.887955,...,5067.518441,4680.967684,4378.585645,4230.923209,3971.862282,3890.484954,3928.581835,4022.806053,4128.249826,4278.453378

Feature: spectral_bandwidth

,0,1,2,3,4,5,6,7,8,9,...,206,207,208,209,210,211,212,213,214,215
0,4317.705763,4241.620245,3764.478469,3102.941045,2587.063385,2375.034496,2266.970605,2138.18024,2141.049603,2112.659337,...,1282.843748,1538.289498,1647.334559,1606.466902,1534.741207,1504.182463,1461.898525,1388.454018,1453.933675,1711.389611

Feature: spectral_rolloff

,0,1,2,3,4,5,6,7,8,9,...,206,207,208,209,210,211,212,213,214,215
0,13000.0,12156.25,10078.125,7750.0,6421.875,6343.75,6312.5,6078.125,6203.125,6015.625,...,6109.375,6093.75,5968.75,5796.875,5703.125,5515.625,5375.0,5375.0,5609.375,6031.25

Feature: zero_crossing_rate

,0,1,2,3,4,5,6,7,8,9,...,206,207,208,209,210,211,212,213,214,215
0,0.223633,0.297852,0.361328,0.295898,0.250488,0.234863,0.235352,0.245117,0.246582,0.242676,...,0.323242,0.3125,0.288086,0.258301,0.239258,0.218262,0.212891,0.219727,0.186035,0.133789

Feature: rms

,0,1,2,3,4,5,6,7,8,9,...,206,207,208,209,210,211,212,213,214,215
0,0.000013,0.000031,0.000073,0.000177,0.00027,0.000456,0.000616,0.000727,0.000869,0.000953,...,0.090907,0.066837,0.030106,0.029994,0.035177,0.04654,0.061427,0.067807,0.066481,0.057839

### Aggrégation et sauvegarde de ces features dans X.npy et y.npy

In [26]:
def aggregate_features(features):
    aggregated_features = {}
    for key, value in features.items():
        aggregated_features[key] = {
            'mean': np.mean(value, axis=1),
            'std': np.std(value, axis=1),
            'min': np.min(value, axis=1),
            'max': np.max(value, axis=1)
        }
    return aggregated_features

def format_features(aggregated_features):
    formatted_features = []
    for key in aggregated_features:
        for stat in aggregated_features[key]:
            formatted_features.extend(aggregated_features[key][stat])
    return np.array(formatted_features)

In [27]:
ogg_file_path = './birdclef-2024/train_audio/asbfly/XC49755.ogg'
max_length = 22050 * 5  # For example, 5 seconds at a sample rate of 22050 Hz

# Extract and aggregate features
features = extract_audio_features(ogg_file_path, max_length)
aggregated_features = aggregate_features(features)

# Format features for model input
formatted_features = format_features(aggregated_features)

print(formatted_features.shape)
print(formatted_features)

(684,)
[-6.78951492e+01 -7.15780563e+01 -7.08037796e+01 -7.23653183e+01
 -7.57353897e+01 -7.60923386e+01 -7.72794800e+01 -7.69549332e+01
 -7.69534836e+01 -7.48166885e+01 -7.59738770e+01 -7.50231247e+01
 -7.48816299e+01 -7.21270599e+01 -7.18847809e+01 -6.99784622e+01
 -6.92440186e+01 -6.64677048e+01 -6.55641174e+01 -6.29078369e+01
 -6.35348587e+01 -6.19041214e+01 -6.14968338e+01 -6.00429764e+01
 -5.98880310e+01 -5.87049522e+01 -5.84747009e+01 -5.72715302e+01
 -5.75240135e+01 -5.58471909e+01 -5.55498390e+01 -5.40977554e+01
 -5.38592224e+01 -5.26902885e+01 -5.27443390e+01 -5.14852295e+01
 -5.19623528e+01 -5.10422821e+01 -5.14217949e+01 -5.06474037e+01
 -5.04771423e+01 -4.96308174e+01 -5.02442932e+01 -4.85827980e+01
 -4.86090584e+01 -4.86892662e+01 -4.79537125e+01 -4.74637413e+01
 -4.74799538e+01 -4.70840149e+01 -4.66258774e+01 -4.66038132e+01
 -4.59247398e+01 -4.57369804e+01 -4.46376724e+01 -4.42834740e+01
 -4.41352196e+01 -4.43094559e+01 -4.40298653e+01 -4.37026901e+01
 -4.32755165e+01 -4.15394707e+01 -3.99824142e+01 -3.92749367e+01
 -3.92779465e+01 -3.87621880e+01 -3.89020996e+01 -3.95993690e+01
 -3.94569855e+01 -3.88339272e+01 -3.77464409e+01 -3.76755600e+01
 -3.86658936e+01 -3.90819778e+01 -4.00564690e+01 -3.94911041e+01
 -3.94883385e+01 -3.96045341e+01 -3.94877930e+01 -3.88125076e+01
 -3.85692368e+01 -3.84432793e+01 -3.79438934e+01 -3.67786636e+01
 -3.60531273e+01 -3.50859528e+01 -3.31388969e+01 -3.15234241e+01
 -3.29588699e+01 -3.34340057e+01 -3.32153320e+01 -3.30964012e+01
 -3.21221428e+01 -3.20766640e+01 -3.23976784e+01 -3.35128937e+01
 -3.53165016e+01 -3.57124748e+01 -3.53675652e+01 -3.51138268e+01
 -3.53335991e+01 -3.51394196e+01 -3.54274139e+01 -3.58785095e+01
 -3.50933571e+01 -3.49577332e+01 -3.44668770e+01 -3.33479576e+01
 -3.35960121e+01 -3.35661087e+01 -3.43455620e+01 -3.52197037e+01
 -3.56412086e+01 -3.67417564e+01 -3.71535378e+01 -3.82551422e+01
 -3.89039726e+01 -3.93453941e+01 -4.11509705e+01 -4.36231461e+01
 -4.62478600e+01 -4.63357735e+01 -4.67927780e+01 -4.65924492e+01
 -4.74542236e+01 -4.95269623e+01 -5.05189056e+01 -5.26859665e+01
  6.56298780e+00  6.18675661e+00  6.55344200e+00  5.51749706e+00
  4.18040562e+00  4.23089838e+00  3.52300286e+00  3.76272726e+00
  3.88103318e+00  4.66801214e+00  4.14626074e+00  4.57999372e+00
  4.80571079e+00  5.48072958e+00  5.57625818e+00  6.21432972e+00
  6.24613523e+00  6.18532991e+00  6.36747408e+00  6.70572090e+00
  7.04883480e+00  6.95166445e+00  7.01741838e+00  7.15030193e+00
  6.66945219e+00  6.77303457e+00  6.60638571e+00  6.78836203e+00
  7.33285475e+00  7.65487719e+00  7.20324326e+00  7.25675488e+00
  7.44987154e+00  7.43501377e+00  7.61926556e+00  7.73002243e+00
  8.07750893e+00  8.22564793e+00  8.29813480e+00  8.07737732e+00
  7.72396040e+00  7.92969036e+00  7.91483164e+00  7.62226820e+00
  8.00218964e+00  7.69910574e+00  7.59039450e+00  7.76663017e+00
  8.30974960e+00  8.12859058e+00  8.16521549e+00  8.16108990e+00
  8.06208038e+00  8.64977837e+00  7.88691998e+00  7.88651371e+00
  8.45182991e+00  8.15819263e+00  8.03371143e+00  7.80946207e+00
  8.20490646e+00  8.17265511e+00  8.35328579e+00  8.57586479e+00
  8.34617424e+00  8.30582714e+00  8.58960819e+00  8.80618191e+00
  8.86267757e+00  1.05642033e+01  1.14022331e+01  1.11419153e+01
  1.06528606e+01  9.42436409e+00  9.12918854e+00  9.68060970e+00
  9.20140266e+00  9.09740639e+00  9.50028229e+00  9.99795818e+00
  9.65746117e+00  9.29731369e+00  9.82576466e+00  1.01280441e+01
  1.06159306e+01  1.11368818e+01  1.23328352e+01  1.34491043e+01
  1.18223820e+01  1.10503883e+01  1.09108934e+01  1.06719265e+01
  1.09011621e+01  1.12801561e+01  1.20857611e+01  1.12677145e+01
  1.08428488e+01  1.07253704e+01  1.10011864e+01  1.18069811e+01
  1.18015528e+01  1.22768888e+01  1.24530249e+01  1.22428036e+01
  1.28905382e+01  1.36546593e+01  1.39125195e+01  1.42805147e+01
  1.41864090e+01  1.46822739e+01  1.43236561e+01  1.40023136e+01
  1.32522650e+01  1.20269718e+01  1.24992142e+01  1.25431204e+01
  1.28116131e+01  1.27642851e+01  1.19424372e+01  1.12910728e+01
  1.11514635e+01  1.02449818e+01  1.11749325e+01  1.22489347e+01
  1.25241880e+01  1.15843544e+01  1.16579781e+01  1.18155575e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01 -8.00000000e+01
 -5.58989906e+01 -5.53959656e+01 -5.41812820e+01 -5.73549004e+01
 -5.83251114e+01 -5.71344910e+01 -5.75621948e+01 -5.79604912e+01
 -5.83976440e+01 -5.69162712e+01 -5.75878448e+01 -5.60618744e+01
 -5.50282898e+01 -5.40371666e+01 -5.43599167e+01 -5.18604851e+01
 -5.38039932e+01 -5.16452942e+01 -5.41225166e+01 -5.16967049e+01
 -5.20693436e+01 -4.94093742e+01 -4.70459862e+01 -4.82545700e+01
 -4.81084366e+01 -4.82258759e+01 -4.76104050e+01 -4.33761902e+01
 -4.47535896e+01 -4.39473228e+01 -4.41831741e+01 -4.31752701e+01
 -4.27493286e+01 -4.07317657e+01 -4.05458221e+01 -3.97431412e+01
 -4.04049149e+01 -3.68087997e+01 -3.79459763e+01 -3.91301956e+01
 -4.03443451e+01 -3.89789505e+01 -3.88422241e+01 -3.70712051e+01
 -3.79855614e+01 -3.90382576e+01 -3.56820068e+01 -3.58552933e+01
 -3.61914825e+01 -3.70150146e+01 -3.58783379e+01 -3.54745064e+01
 -3.41478653e+01 -3.54403305e+01 -3.49919548e+01 -3.37266922e+01
 -3.25184631e+01 -3.41697502e+01 -3.31934738e+01 -3.42239304e+01
 -2.90324287e+01 -2.81320705e+01 -2.88013763e+01 -2.80316296e+01
 -2.82570438e+01 -2.85703602e+01 -2.78563747e+01 -2.27793846e+01
 -2.02830105e+01 -9.31635284e+00 -6.44812393e+00 -1.29913139e+01
 -1.47169743e+01 -2.24343472e+01 -2.91979122e+01 -2.57494621e+01
 -2.54320393e+01 -2.24489536e+01 -2.46336021e+01 -2.46523037e+01
 -2.11715050e+01 -2.32916107e+01 -2.47804298e+01 -2.35608330e+01
 -2.10312634e+01 -1.83106289e+01 -1.32193012e+01 -1.04374714e+01
 -1.37160969e+01 -1.26200771e+01 -1.11487722e+01 -1.67393608e+01
 -9.03981781e+00 -7.31603146e+00 -8.54920673e+00 -9.53508854e+00
 -7.58930969e+00 -1.09238672e+01 -1.24443722e+01 -1.01276379e+01
 -9.14618683e+00 -9.87414932e+00 -6.04185486e+00 -9.62997150e+00
 -7.19623661e+00 -1.26617241e+00 -3.28722000e+00 -3.13824272e+00
 -2.87443161e-01 -1.68604660e+00  0.00000000e+00 -6.46774292e-01
 -3.31578827e+00 -8.79345512e+00 -5.26008797e+00 -3.25497818e+00
 -1.62715340e+00 -2.09276581e+00 -6.58005238e+00 -1.85611172e+01
 -2.38423748e+01 -2.52900162e+01 -2.22083569e+01 -1.10508595e+01
 -8.56939316e+00 -1.62574615e+01 -1.27492228e+01 -1.36126022e+01
 -3.78031830e+02 -9.77883530e+00 -1.62413513e+02  3.93792496e+01
 -4.95024414e+01 -6.25754952e-01 -3.73189092e+00 -7.72479630e+00
  5.14817286e+00 -9.43656087e-01  8.90023994e+00  4.81888485e+00
  2.91284639e-02  8.03989258e+01  1.78389111e+01  3.11695156e+01
  1.88223629e+01  1.95934696e+01  9.88203430e+00  9.81475258e+00
  9.35540485e+00  6.19377613e+00  6.64263916e+00  8.38669777e+00
  7.03470707e+00  6.25368309e+00 -6.95373413e+02 -6.44159851e+01
 -1.98375702e+02 -2.97236629e-03 -9.14127884e+01 -1.87219849e+01
 -2.72821999e+01 -3.06997910e+01 -1.04681206e+01 -1.74845238e+01
 -1.79145699e+01 -1.83506126e+01 -1.67871075e+01 -2.93432343e+02
  2.18190041e+01  0.00000000e+00  8.81841202e+01  1.15288992e+01
  2.74191780e+01  1.70098858e+01  1.13695374e+01  2.45029984e+01
  2.21737156e+01  2.91054955e+01  2.93264065e+01  2.02210350e+01
  3.57199669e-01  3.07124913e-01  3.35543215e-01  3.79172206e-01
  3.74025345e-01  3.68796766e-01  5.04714668e-01  5.14655292e-01
  4.76456851e-01  5.64261734e-01  4.03101981e-01  3.45245808e-01
  2.93734074e-01  2.65951812e-01  2.80152529e-01  2.76178837e-01
  2.77236521e-01  2.68116444e-01  3.31215084e-01  3.24809521e-01
  3.44703078e-01  3.66285771e-01  2.83933997e-01  2.77644485e-01
  1.67002657e-03  3.50483740e-03  3.55487806e-03  3.75877088e-03
  6.80759549e-03  1.12461373e-02  1.24585899e-02  4.05499293e-03
  1.84830569e-03  1.53691531e-03  1.69276039e-03  1.32982631e-03
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00
  1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00
  1.62773277e+01  1.06704757e+01  1.42380681e+01  1.45769910e+01
  1.70175486e+01  1.90484413e+01  6.93276178e+01  5.76273238e+00
  3.39276026e+00  3.19840501e+00  3.02201156e+00  3.37178078e+00
  3.76862762e+00  9.12752491e+00  5.12270923e-01  1.33191088e+00
  6.94619444e+00  7.49248851e+00  9.89702713e+00  1.29031459e+01
  1.64578896e+01  4.26313984e+01  2.37981382e+01  2.72607590e+01
  2.54604875e+01  2.47335738e+01  3.22490138e+01  8.46284054e+01
  3.01676145e-02 -4.96030774e-02  8.57827611e-03 -1.20755105e-02
 -2.17345898e-02  2.96799583e-02  7.32132151e-02  8.62107506e-02
  8.40756663e-02  1.11186092e-01  4.14829636e-02  4.96818321e-02
 -1.32700129e-01 -3.35049976e-01 -2.59177800e-01 -3.18522710e-01
 -1.80899388e-01 -8.71331068e-02  3.30933276e-01  1.39883337e-01
  2.68008497e-01  2.97367979e-01  8.07791691e-02  2.04888605e-01
  4.20911135e+03  5.54060368e+02  3.51706074e+03  7.67759453e+03
  1.70350725e+03  3.90775022e+02  9.74244632e+02  4.31770576e+03
  5.86841725e+03  8.78995727e+02  4.96875000e+03  1.30000000e+04
  2.51867224e-01  4.45658672e-02  1.33789062e-01  4.06738281e-01
  3.53122093e-02  3.67540419e-02  1.29457030e-05  1.58307001e-01]

In [28]:

def load_data(file_paths, labels, max_length=22050*5):
    X = []
    y = []

    for file_path, label in zip(file_paths, labels):
        features = extract_audio_features(file_path, max_length)
        aggregated_features = aggregate_features(features)
        formatted_features = format_features(aggregated_features)
        X.append(formatted_features)
        y.append(label)
        # print(len(X), len(X[-1]),y)
        if len(X) % 100 == 0:
            print(f"Processed {len(X)} files")
    return np.array(X), np.array(y)

In [30]:
# Assuming df_train is already loaded in your notebook
file_paths = df_train['filename'].apply(lambda x : "./birdclef-2024/train_audio/" + x ).tolist()
labels = df_train['primary_label'].astype('category').cat.codes.tolist()

# Load data
# X, y = load_data(file_paths, labels)
X, y = np.load('X.npy'), np.load('y.npy')# load_data(file_paths, labels)

In [31]:
# save the x and y

np.save('X.npy', X)
np.save('y.npy', y)